version: '3.7'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
  blog-app:
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "mysite.wsgi"]
    image: blog-app
    depends_on:
      - postgres
      - blog-migrations
    build:
      context:
        .
    environment: &env
      PYTHONUNBUFFERED: 1
      POSTGRES_HOST: postgres
      DEBUG: 0
    ports:
      - "8000:8000"
  blog-migrations:
    image: blog-app
    command: ["python", "manage.py", "migrate"]
    environment: *env
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: polls
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: polls
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  db-data: null
