# Generated by Django 4.2.2 on 2023-07-20 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_vote"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
