# Generated by Django 4.2.2 on 2023-07-20 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_like_dislike_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
