# Generated by Django 4.2.2 on 2023-07-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_delete_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="users",
        ),
        migrations.AddField(
            model_name="post",
            name="dislikes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="DisLike",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
