# Generated by Django 4.2.2 on 2023-07-24 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0009_remove_like_users_post_dislikes_post_likes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="dislikes",
            new_name="down_vote",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="likes",
            new_name="up_vote",
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("up_vote", models.PositiveIntegerField(verbose_name=1)),
                ("down_vote", models.PositiveIntegerField(verbose_name=-1)),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.post"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
