# Generated by Django 4.2.2 on 2023-07-24 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_rename_dislikes_post_down_vote_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vote",
            old_name="post_id",
            new_name="post",
        ),
        migrations.RenameField(
            model_name="vote",
            old_name="user_id",
            new_name="user",
        ),
    ]
