# Generated by Django 4.2.2 on 2023-07-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_rename_post_id_vote_post_rename_user_id_vote_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="down_vote",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="up_vote",
        ),
        migrations.AddField(
            model_name="vote",
            name="up",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
