# Generated by Django 4.2.2 on 2023-07-26 11:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0012_remove_vote_down_vote_remove_vote_up_vote_vote_up"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("post", "user")},
        ),
    ]
