# Generated by Django 4.2.2 on 2023-07-26 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_alter_vote_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="down_vote",
        ),
        migrations.RemoveField(
            model_name="post",
            name="up_vote",
        ),
    ]
