# Generated by Django 4.2.2 on 2023-07-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_remove_post_down_vote_remove_post_up_vote"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="blog.tag"
            ),
        ),
    ]
